"""empty message

Revision ID: 09daf4af634f
Revises: None
Create Date: 2018-09-03 12:39:27.368093

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '09daf4af634f'
down_revision = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_headers',
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('header_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['headers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process_headers')
    op.drop_table('headers')
    # ### end Alembic commands ###
