"""empty message

Revision ID: 1bc03db320cc
Revises: 09daf4af634f
Create Date: 2018-09-03 12:43:19.641639

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '1bc03db320cc'
down_revision = '09daf4af634f'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('headers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('headers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
