"""empty message

Revision ID: 69046c7172e0
Revises: 1bc03db320cc
Create Date: 2018-09-03 14:55:05.421085

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '69046c7172e0'
down_revision = '1bc03db320cc'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processes', sa.Column('duration', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processes', 'duration')
    # ### end Alembic commands ###
